# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Simon Dorrer/JKU-Linz/Master/Semester 2/Master-Thesis/FPGA-Design/tbs_core/vivado/tbs_core_all_board/tbs_core_all_board.srcs/sources_1/ip/pll_50MHz/pll_50MHz.xci
# IP: The module: 'pll_50MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Simon Dorrer/JKU-Linz/Master/Semester 2/Master-Thesis/FPGA-Design/tbs_core/vivado/tbs_core_all_board/tbs_core_all_board.gen/sources_1/ip/pll_50MHz/pll_50MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_50MHz'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Simon Dorrer/JKU-Linz/Master/Semester 2/Master-Thesis/FPGA-Design/tbs_core/vivado/tbs_core_all_board/tbs_core_all_board.gen/sources_1/ip/pll_50MHz/pll_50MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_50MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Simon Dorrer/JKU-Linz/Master/Semester 2/Master-Thesis/FPGA-Design/tbs_core/vivado/tbs_core_all_board/tbs_core_all_board.gen/sources_1/ip/pll_50MHz/pll_50MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_50MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Simon Dorrer/JKU-Linz/Master/Semester 2/Master-Thesis/FPGA-Design/tbs_core/vivado/tbs_core_all_board/tbs_core_all_board.srcs/sources_1/ip/pll_50MHz/pll_50MHz.xci
# IP: The module: 'pll_50MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Simon Dorrer/JKU-Linz/Master/Semester 2/Master-Thesis/FPGA-Design/tbs_core/vivado/tbs_core_all_board/tbs_core_all_board.gen/sources_1/ip/pll_50MHz/pll_50MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_50MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Simon Dorrer/JKU-Linz/Master/Semester 2/Master-Thesis/FPGA-Design/tbs_core/vivado/tbs_core_all_board/tbs_core_all_board.gen/sources_1/ip/pll_50MHz/pll_50MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_50MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Simon Dorrer/JKU-Linz/Master/Semester 2/Master-Thesis/FPGA-Design/tbs_core/vivado/tbs_core_all_board/tbs_core_all_board.gen/sources_1/ip/pll_50MHz/pll_50MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_50MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
